name: Dynamic_Workflow

on:
  push:
    branches:
      - main

jobs:
  Checkout_Repository:
    name: Install Git
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Install Git
        run: sudo apt-get install -y git

  Set_ENV:
    name: Set_ENVIRONMENT
    runs-on: ubuntu-latest
    needs:  Checkout_Repository
    
    steps:
      - name: Set_ENVIRONMENT
        run: sudo apt-get install -y nginx

  Build:
    name: Build
    runs-on: ubuntu-latest
    needs: Set_ENV
    
    steps:
      - name: Echo Build Success
        run: echo "Build successful"

  run_tests:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: Build
    
    steps:
      - name: Run Tests
        run: |
          # Add commands to run tests here
          echo "Running tests..."

  dev_deploy:
    name: dev_deploy
    runs-on: ubuntu-latest
    needs: run_tests
      
    steps:
      - name: SSH into Dev Server and Execute Commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Add commands to be executed on the server after SSH connection
            echo "Connected to server"
            cd /home/ubuntu/cicd-project
            git pull origin main
            sudo cp * /var/www/html/
            echo "website upgradation done"


  prod_deploy:
    name: prod_deploy
    runs-on: ubuntu-latest
    needs: run_tests
    environment:
      name: production
    steps:
      - name: SSH into PROD Server and Execute Commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Add commands to be executed on the server after SSH connection
            echo "Connected to server"
            cd /home/ubuntu/cicd-project
            git pull origin main
            sudo cp * /var/www/html/
            echo "website upgradation done"

